version: '3'
services:
  db-recipes:
    container_name: db-prices
    image: postgres:16
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prices-db