spring:
  application:
    name: 'recipes-api'
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
#tmp
  jpa:
    hibernate:
      ddl-auto: 'create'
#tmp