spring:
  application:
    name: 'recipes-api'
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/recipes-db
    username: postgres
    password: postgres
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
  jpa:
    hibernate:
      ddl-auto: 'create'
    show-sql: false