server:
  port: 8092
spring:
  application:
    name: "goods-collector"
  datasource:
    url: jdbc:h2:mem:products_db
    username: sa
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
  kafka:
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false

magnit-api:
  url: "http://localhost:8091"

cron: "0 0 12 * * ?"